### ISSUE TITLE
add staging env with staging db

### ISSUE THREAD

**Issue by bradnoble** [bradnoble/msc-vuejs#104]
We should be able to QA in a staging environment, and also QA against a db that is not our production environment.

**Comment by bradnoble** [comment]
Check it out: https://msc-staging.mybluemix.net/

**Comment by seekingsnowflakes** [comment]
Generally looks good. The graphic on the sign-in page gives the little missing-file icon though. I assume that's not something we should worry about here.

![image](https://user-images.githubusercontent.com/34328388/54167864-363cdf00-4442-11e9-8ab1-094997fc020f.png)

**Comment by bradnoble** [comment]
@seekingsnowflakes this should be closed, b/c staging is live and has been for a while. If we have issues with images, that should be captured that in a separate issue.

**Comment by seekingsnowflakes** [comment]
OK.
