### ISSUE TITLE
Remove Test Household

### ISSUE THREAD

**Issue by seekingsnowflakes** [bradnoble/msc-vuejs#107]
@bradnoble needs to remove blank household/people entries.

May be coming from this test household that is empty:

![image](https://user-images.githubusercontent.com/34328388/50806106-42ca7d00-12c3-11e9-87fd-23c8ee87f44e.png)

Causes blank people in "active" because that is the default.

![image](https://user-images.githubusercontent.com/34328388/50806124-5d045b00-12c3-11e9-9885-53bb6e1a739e.png)

Admin role cannot delete empty household. "Cannot get POST\" error.

**Comment by bradnoble** [comment]
Added an alert to /admin that shows you the issues to resolve, and the forms in /admin allow you to resolve them.

**Comment by seekingsnowflakes** [comment]
@bradnoble should I try actually deleting one of them to verify? Snazzy though.

**Comment by bradnoble** [comment]
@seekingsnowflakes this is good to go to test on staging.

**Comment by seekingsnowflakes** [comment]
Deleted one. Good to go.
