### ISSUE TITLE
View categories of member entries

### ISSUE THREAD

**Issue by seekingsnowflakes** [bradnoble/msc-vuejs#112]
I have gotten used to being able to click a member status and get all the members associated with it. I have had to use it a bunch (when not having the CSV properly download) to cross-reference current member data and find discrepancies between an old download and current member status.

Use case 1: If you don't know for sure how to spell a name (i.e. type "Jeff" but looking for "Geoff").

Use case 2: Membership committee wants to look at active members to decide who to recruit for officer/committee positions.

Use case 3: Admin created a new household and wants to see if it was created properly (or find the extra "active" member with unknown name).

A properly-working CSV download will mitigate most of the admin-type stuff I needed for this function for, but this is a few use cases for the website version.

**Comment by seekingsnowflakes** [comment]
Realizing now that the "report preview" might be enough. Had thought we restricted the .CSV to admin (because of issue #67). If it's available to members, maybe that's enough, but not sure why the .CSV availability was changed.

**Comment by seekingsnowflakes** [comment]
Also the "Active Member" quicklink shows an empty page.

**Comment by bradnoble** [comment]
Working on turning the statuses in the Tally section of the /members section into links that will yield search results.

**Comment by bradnoble** [comment]
@seekingsnowflakes Click the links in the Tally section: https://msc-staging.mybluemix.net/#/members

**Comment by bradnoble** [comment]
I see your note about the CSV section being restricted to /admin. Reopened #67 and added it to this milestone. I'll fix it.

**Comment by seekingsnowflakes** [comment]
This works, though I sort of expected the "status" button to take you back to the main household page. There is the link at the top though.

**Comment by bradnoble** [comment]
@seekingsnowflakes do you mean that you thought the 'status' label would take you back to the main membership page?

**Comment by seekingsnowflakes** [comment]
@bradnoble Yes, main membership page. Whoops.
