### ISSUE TITLE
Member DB: state-of-residence is required even when residence is not USA

### ISSUE THREAD

**Issue by jcjcx1** [bradnoble/msc-vuejs#114]
The Member database field for 'state of residence' is a required field. This does not make sense when a person's residence is outside of the USA. The best fix would be to only make this field required on the condition that the country is USA.

**Comment by bradnoble** [comment]
Looking at this @jcjcx1 it appears that Kazakhztan does in fact have states, or regions. In which region / state is the person in question?

**Comment by jcjcx1** [comment]
Actually Joe's city "Almaty" is also in the state of "Almaty" (like NY, NY) . Does the state field accept general text or only the 2 character US state abbreviations.

**Comment by bradnoble** [comment]
State field accepts text. I have changed it to State/Region. Will push to
staging tomorrow.

**Comment by bradnoble** [comment]
@jcjcx1 ok to close? state/region pushed to production

**Comment by jcjcx1** [comment]
The code on the staging site is fine (your message above says that it is pushed to production, but I don't see the change there?). (If you haven't actually pushed to production yet please don't forget to change the "version" number and "year" in the footer banner)

**Comment by bradnoble** [comment]
@jcjcx1 do a hard refresh on production
