### ISSUE TITLE
Active Member link from homepage broken (production)

### ISSUE THREAD

**Issue by seekingsnowflakes** [bradnoble/msc-vuejs#115]
http://www.montclairskiclub.com/#/members/status/active goes to a blank page.

Proper link:

http://www.montclairskiclub.com/#/members/search?drilldown=%5B%22status%22,%22active%22%5D

**Comment by bradnoble** [comment]
@seekingsnowflakes please review, fix is live on production

**Comment by seekingsnowflakes** [comment]
Looks good.
