### ISSUE TITLE
Membership: Display member category totals w/ list

### ISSUE THREAD

**Issue by idevtech** [bradnoble/msc-vuejs#15]
Display the total count for each membership category on the membership list. page. (Feedback from Frank D.)

**Comment by bradnoble** [comment]
List now shows totals when you search by facet.

https://www.dropbox.com/s/y2d69f3axryr19j/Screenshot%202018-05-29%2007.40.09.png?dl=0

**Comment by idevtech** [comment]
The intention of this request from Frank as membership chair is there should be a place to easily see the count for each membership category. Apparently this was available in the old site. While the counts are displayed as each membership category is selected this isn't the most efficient way to get this information.

I would propose that under the breadcrumbs at the top of the page there be a horizontal list of each category w/ the count. Not sure how this is done in our DB but in SQL it would be a simple Count() query to return all the counts by category. Happy to help figure this out.

**Comment by seekingsnowflakes** [comment]
This has been implemented.

![image](https://user-images.githubusercontent.com/34328388/49128825-289c8880-f29b-11e8-9326-8df9688888c1.png)
