### ISSUE TITLE
Limit CSV file to relevant data fields

### ISSUE THREAD

**Issue by idevtech** [bradnoble/msc-vuejs#18]
The CSV file appears to have all the member fields including internal fields. Limit the fields to the ones that would be used.

**Comment by bradnoble** [comment]
Fields still needed: mail-news, mail-list (both boolean)

**Comment by seekingsnowflakes** [comment]
Note that current CSV does not have mail-news, mail-list (https://github.com/bradnoble/msc-vuejs/issues/9) - needs to be reviewed by board.

When added, country should also be part of the address. (https://github.com/bradnoble/msc-vuejs/issues/108)

Need to investigate child phone # format (https://github.com/bradnoble/msc-vuejs/issues/79)

May want to include member year and/or birthyear/birthyear analogue when those fields are implemented. https://github.com/bradnoble/msc-vuejs/issues/92, https://github.com/bradnoble/msc-vuejs/issues/23)

**Comment by bradnoble** [comment]
This is live on staging.

**Comment by seekingsnowflakes** [comment]
Address export has only address line 1 (number and street) and line 2 (apt/unit number) and does not have town, state, zip, country.

**Comment by bradnoble** [comment]
This is resolved on staging.

**Comment by bradnoble** [comment]
@seekingsnowflakes please verify

**Comment by seekingsnowflakes** [comment]
@bradnoble Should we export the work phone # also? I might be one of the few people that use it at this point, though. Otherwise looks like what we discussed.

Will set to verified.

**Comment by bradnoble** [comment]
i've committed a fix to show the work_phone in the CSV download. Will push
to staging later today.
