### ISSUE TITLE
Member user can edit information

### ISSUE THREAD

**Issue by idevtech** [bradnoble/msc-vuejs#19]
From Jim C.
Well, at least it looks like they have edit privileges, but they actually don't. Clicking on pencil gets to an edit page, but no changes can be submitted.

**Comment by idevtech** [comment]
The edit icon (pencil) should be hidden when the user does not have authorization for that action.

**Comment by bradnoble** [comment]
This is handled (but not yet live) b/c the "admin" section will be the only interface from which an admin can edit household info, and the admin section will only be accessible by admins.

**Comment by seekingsnowflakes** [comment]
Admin section is now available. HOWEVER, if someone has the admin URL, can still make edits without being logged in as admin. Without manually entering the URL, though, this page is not accessible.

**Comment by seekingsnowflakes** [comment]
Raising priority to "critical" due to relative priority.

**Comment by idevtech** [comment]
I have added logic (routes.js) to restrict access to any client URL based upon the user role(s) and the new "roles" meta data attribute in the route definitions.

**Comment by seekingsnowflakes** [comment]
Copied URL from first member edit page. Logged out, entered URL, stayed on login page. Logged in as member, entered URL, stayed on landing page.

Looks good on staging area.
