### ISSUE TITLE
Default sort for 'list' should be first name

### ISSUE THREAD

**Issue by bradnoble** [bradnoble/msc-vuejs#21]
This may complicate the views in Cloudant -- testing on 3/5 suggested that reordering the keys in the 'householdsAndPeople' view broke the 'admin' view. Needs further investigation.

**Comment by idevtech** [comment]
Duplicate of #17

**Comment by seekingsnowflakes** [comment]
Conflicts with #29 and #17. Review for closure - believe group decision has decided on last,first.

**Comment by seekingsnowflakes** [comment]
Closing as duplicate.
