### ISSUE TITLE
add household hangs during save

### ISSUE THREAD

**Issue by jcjcx1** [bradnoble/msc-vuejs#28]
![image](https://user-images.githubusercontent.com/26268235/38006491-436c7e48-3213-11e8-81f2-6104ab745ee2.png)

then after about a minute....

![image](https://user-images.githubusercontent.com/26268235/38006525-62faced6-3213-11e8-9d66-04147d46b775.png)

(Not sure if this happens because the household name "Castellano" already exists (I was trying to move Rick into his own household since he doesn't live with me anymore)

**Comment by seekingsnowflakes** [comment]
Was able to add new household without hanging. Including a new "Castellano" household. Still can't move people from one household to another, but that's a separate logged issue.
