### ISSUE TITLE
Eliminate household phone number

### ISSUE THREAD

**Issue by idevtech** [bradnoble/msc-vuejs#30]
Household phone number is legacy data from the time when most people had a home phone. Current, more and more people have just a mobile phone number. This % will only increase going forward. Given the paradigm shift of a new website for the membership let's eliminate household phone now rather than wait until only a few members have one.

**Comment by seekingsnowflakes** [comment]
Don't know if I totally agree. If remove from household, should have an option for a home phone for a particular person. Some people will still prefer landline, especially if house doesn't have good cell service.

**Comment by idevtech** [comment]
What I'm suggesting is phone numbers (and email addresses) only be associated w/ individuals rather than w/ households. An individual could have any type of phone number, i.e,, landline or mobile, that would be classified as work, home, mobile, etc. Each person could choose what phone number(s) to associate w/ their profile. If all the people in a household wanted to have the house landline as each of their phone numbers they could do so.

**Comment by bradnoble** [comment]
@idevtech                        @seekingsnowflakes                        are we agreed that we can remove the household phone number?

**Comment by seekingsnowflakes** [comment]
I don't think we should remove it without moving those numbers to the adults in the household as home numbers.

**Comment by seekingsnowflakes** [comment]
Per slack discussion, OK to leave database field for now. Closing issue.
