### ISSUE TITLE
Membership: Condense household information in the member list 

### ISSUE THREAD

**Issue by idevtech** [bradnoble/msc-vuejs#32]
The member list would be easier to read if household information wasn't repeated for each member in the household. One solution would be to create one row per household, listing each member and associated information then displayed the household information just once on the right side.

This could be achieved w/ a nested grid layout.

row
cell1 
row(s) w/ member cell data
cell2 
rows w/ household data

**Comment by idevtech** [comment]
Admin page for membership list kind of has this format, reversed from what I'm suggesting, i.e., household is on the left instead of the right as proposed above.

**Comment by bradnoble** [comment]
This is dealt with on the new membership list -- household info is pushed out to the household detail page.
