### ISSUE TITLE
Member list should default to empty w/ informational message

### ISSUE THREAD

**Issue by idevtech** [bradnoble/msc-vuejs#34]
When the member list page first displays the list should be empty and in place of a member name row a brief instructional message should be displayed informing the user of the purpose for the page. There is the placeholder in the search box but something more explicit would be even better.

**Comment by seekingsnowflakes** [comment]
I've gotten used to seeing the whole membership list, so I was surprised to see this implemented. The old site has an option to "view the whole list", which this does as well, but only after something has been searched for. Perhaps we need an "all" button for the main view?

I think this is also missing the request for a little more informational text.

Setting to "Review Needed" for clarification if any other changes need to be made.

**Comment by seekingsnowflakes** [comment]
Alternate request: Add "all" button (next to active, life, etc) to get to the whole list from the start.

**Comment by seekingsnowflakes** [comment]
All button has been implemented.
