### ISSUE TITLE
Household page does not return to previous search results in member list

### ISSUE THREAD

**Issue by idevtech** [bradnoble/msc-vuejs#36]
To replicate:

1. Login as admin (for now due to #35 )
2. Select a household name
3. Household page w/ member data is displayed
4. Click MembershipList breadcrumb or "List" link in footer
5. Membership list is displayed but any previously entered search criteria/filter is not retained.

Expected behavior:
Returning to the membership list page from viewing a household should retain the previous filter criteria.

This could be achieved by a) passing the filter criteria to the household page and then using it to construct the query string for the link back to the Membership List page or b) writing a cookie w/ the filter criteria.

**Comment by seekingsnowflakes** [comment]
Tried both a "back" browser button and an "alt + <--" keyboard shortcut and was brought back to the filtered search results. Looks good.

**Comment by seekingsnowflakes** [comment]
See #76 also.
