### ISSUE TITLE
Returning to the Membership List page from household requires login

### ISSUE THREAD

**Issue by idevtech** [bradnoble/msc-vuejs#37]
To reproduce:

1. Login as "member"
2. Select household to view household page
3. After household page loads select Membership List breadcrumb or "List" link in footer.
4. When membership page loads user is prompted to login again

Expected behavior:
No login required when returning to Membership List page

**Comment by seekingsnowflakes** [comment]
Authentication work has fixed this. Review with @idevtech for closure.
