### ISSUE TITLE
Resources should be sorted by name

### ISSUE THREAD

**Issue by seekingsnowflakes** [bradnoble/msc-vuejs#41]
Default sort is confusing. Naming is set up to create a document hierarchy, so would like to be able to default sort by name or resort based on column click.

**Comment by idevtech** [comment]
Fixed. For v1 it will sort by Name ascending. We can pursue sort by column header in a subsequent version.

**Comment by seekingsnowflakes** [comment]
Resources are being displayed in ascending name order.
