### ISSUE TITLE
Change search action logic for Admin

### ISSUE THREAD

**Issue by seekingsnowflakes** [bradnoble/msc-vuejs#49]
Search does not occur until four characters are entered.

This is undesirable, particularly for people with short first names. Search should occur when "enter" or "return" is pressed (or add a search button that starts the search), even if fewer than 4 characters have been entered.

3-letter names: Sue, Don, Uwe, Jay, Tab, Jim, Ken, Tom, Eva, Joe, Bob

**Comment by bradnoble** [comment]
Handled this to wait to search until 500 milliseconds after the last keystroke. (Any new keystroke resets the timer.)

**Comment by bradnoble** [comment]
reopening and changing status to 'testing needed'

**Comment by idevtech** [comment]
The list refreshing w/ < 3 chars entered is distracting. I would recommend the list not start refreshing until the 3rd character is entered. With that approach the 500 MS delay is not needed.

**Comment by idevtech** [comment]
The list refreshing w/ < 3 chars entered is distracting and the result set is still quite large which doesn't achieve the intended result of finding a person quickly. I would recommend the list not start refreshing until the 3rd character is entered. The full list for the selected category is displayed by default to if the user isn't certain of the name they can scroll. With that approach the 500 MS delay is not needed.

**Comment by bradnoble** [comment]
I can see having both the timer and the minimum # of characters.

**Comment by seekingsnowflakes** [comment]
Behavior has been changed to requiring "enter". Discuss if this is OBE.

**Comment by seekingsnowflakes** [comment]
"Admin" area has different behavior from member search area now. Need to discuss if new issue should be opened for that or whether to leave it.

**Comment by seekingsnowflakes** [comment]
Per slack discussion, Chris agreed current behavior is fine for now. closing issue.

**Comment by bradnoble** [comment]
Admin section now features a faceted search, similar to the members area. Requires clicking enter, or the submit button.

**Comment by bradnoble** [comment]
Check faceted search in /admin.

**Comment by seekingsnowflakes** [comment]
Looks good on staging site.
