### ISSUE TITLE
CSV has weird characters in download title

### ISSUE THREAD

**Issue by seekingsnowflakes** [bradnoble/msc-vuejs#57]
Just downloaded CSV and it has weird numbers afterward. Might be the time, but it doesn't match my current time. It's 8:10 PM on 5/28 EDT. Download name:

MSC-Membership-List-2018-05-29T00_08_57.234Z.csv

**Comment by bradnoble** [comment]
The date/time stamp is there for uniqueness, and for easy sorting (most recent at the top or bottom of whatever list of files you're looking at on your machine). The data/time itself is ISO, so it likely will not match the time on any one user's machine. 

In your case, you wrote the issue 2 minutes after you downloaded the file, and the date _seems_ wrong b/c in ISO it was already the next day (+4 hours).
