### ISSUE TITLE
CSV download is empty

### ISSUE THREAD

**Issue by seekingsnowflakes** [bradnoble/msc-vuejs#58]
Even after selecting "all" members, CSV download is empty.

![image](https://user-images.githubusercontent.com/34328388/40632321-a0244348-62b3-11e8-8e0e-58b2dfe4a3ff.png)

**Comment by bradnoble** [comment]
merged this fix into develop #61

**Comment by bradnoble** [comment]
Reopening and changing status to "testing needed".

**Comment by seekingsnowflakes** [comment]
![image](https://user-images.githubusercontent.com/34328388/40695204-11d34252-638e-11e8-9393-11344a07b7ca.png)

Looks good
