### ISSUE TITLE
Searching the membership list by name w/o selecting a category doesn't return any names w/o RETURN

### ISSUE THREAD

**Issue by idevtech** [bradnoble/msc-vuejs#71]
To reproduce:

1. Go to Membership list page
2. Enter several characters in the Search by Name text box.

Result:
No names are displayed.

Expected:
The names matching the entered characters would be displayed.

Note: The min chars should be the same as #49

**Comment by idevtech** [comment]
I just found that RETURN after typing characters executes a search. The behavior should be like the other member list autocomplete searching.

**Comment by seekingsnowflakes** [comment]
I also noticed the "return" behavior is a little odd - I think due to the 15 ms wait time I think Brad put in for another bug. It seems to wait that same amount of time once you're passed the main page, even if you press return.

**Comment by seekingsnowflakes** [comment]
Functionality is to now wait until "enter" is pressed. This seems to be a better functionality and avoids some of the other search issues. Discuss as a team before closing.

**Comment by seekingsnowflakes** [comment]
Believe this is OBE now.
