### ISSUE TITLE
Change Membership List page header to "Membership List"

### ISSUE THREAD

**Issue by idevtech** [bradnoble/msc-vuejs#72]
"The MSC Membership List" page header contains unneeded information. "The" doesn't add any context and the user will know they are in the "MSC" site.

**Comment by seekingsnowflakes** [comment]
Not sure what you mean by this, Chris. Screenshot?

Jim has noticed the tab name will change when navigating to a household to the household name. Is this the same thing?

**Comment by seekingsnowflakes** [comment]
Title is now "Membership List." Complete.
