### ISSUE TITLE
Any member name is displayed in search results even if a category is selected.

### ISSUE THREAD

**Issue by idevtech** [bradnoble/msc-vuejs#75]
To reproduce:

1. Go to Membership List page
2. Select Non-Member category to display Membership List/Search page w/ Non-Member category selected.
3. Click in search box
4. Enter "Pel"

The list then displays ALL members whose last names start w/ "Pel" rather than just the non-members.

![screen shot 2018-06-01 at 5 53 17 pm](https://user-images.githubusercontent.com/486002/40865127-dc28f6fe-65c4-11e8-8c41-a5e6f3258736.png)

In addition, the Non-Member category is no longer selected.

**Comment by bradnoble** [comment]
This is intentional. Free text and status are not combinatorial.

**Comment by seekingsnowflakes** [comment]
Need review by team on desired functionality to close. (Is as designed according to Brad)

**Comment by seekingsnowflakes** [comment]
Closing per slack discussion.
