### ISSUE TITLE
Enhancement: Note donation resource document

### ISSUE THREAD

**Issue by seekingsnowflakes** [bradnoble/msc-vuejs#91]
From Frank during beta test: "Under financial and Note Donation. Should there be a reference list of the members that donated their notes?"

**Comment by idevtech** [comment]
I can provide this info from master list.

**Comment by seekingsnowflakes** [comment]
I have created a document with the note donation list as of the April 2018 Newsletter. @idevtech to review or update.

**Comment by idevtech** [comment]
I have cross referenced the NoteDonations document w/ the master spreadsheet of note donations, making some corrections and additions. The PDF version is now available in /Financials.

**Comment by seekingsnowflakes** [comment]
Verified updated file. Complete.
