### ISSUE TITLE
Incorrect login provides no feedback

### ISSUE THREAD

**Issue by seekingsnowflakes** [bradnoble/msc-vuejs#94]
From beta test period: 

No indication of "incorrect info" is given to the user when entering an incorrect username.

Chris indicated a change is waiting on merge/deployment

**Comment by idevtech** [comment]
Fixed v2.00.150

**Comment by seekingsnowflakes** [comment]
Reopen, wait for depolyment

**Comment by seekingsnowflakes** [comment]
Additional notes from Mike Hartman: 

User Name appears to be case sensitive. I found this out when i tried to login from my phone and it automatically capitalized the first character. Ideally user names should not be case-sensitive.  
The password field is case-insensitive.  Passwords should be case-sensitive

**Comment by seekingsnowflakes** [comment]
Tested case-changed username - allows entry.
Tested incorrect password - provides error message.
Closed.
